accounts/urls.py
from django.urls import path
from accounts import views

app_name="accounts"

urlpatterns=[
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
    path('signup/', views.signup, name="signup"),
]

app/urls.py
from django.urls import path
from app import views

urlpatterns=[
    path("echo/", views.echo_page),
    path("liveblog/",views.liveblog_index),
    path("liveblog/posts/<int:post_id>",views.post_partial, name = "post_partial")
]

chat/urls.py
from django.urls import path
from chat import views

app_name = "chat"

urlpatterns=[
    path("",views.index, name="index"),
    path("new/", views.room_new, name="room_new"),
    path("<str:room_pk>/chat/",views.room_chat, name="room_chat"),
    # path("<int:room_pk>/delete/", views.room_delete, name="room_delete"),
]

ecopschat/urls.py
import django.views.generic
from django.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('', include('app.urls')),
    path("", RedirectView.as_view(pattern_name="chat:index"),name="root"),
    path("accounts/", include("accounts.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db.models.signals import post_save, post_delete
import django.db.models.signals
import django.urls
from django.db import models
from app.mixins import ChannelLayerGroupSendMixin


class Post(ChannelLayerGroupSendMixin, models.Model):
    CHANNEL_LAYER_GROUP_NAME = "liveblog"
    title = models.CharField(max_length=100)
    content = models.TextField()

    class Meta:
        ordering = ["-id"]

def post__on_post_save(instance: Post, created: bool, **kwargs):
    if created:
        message_type = "liveblog.post.created"
    else:
        message_type = "liveblog.post.updated"

    post_id = instance.pk
    post_partial_url= django.urls.reverse("post_partial", args=[instance.pk])

    instance.channel_layer_group_send({
        "type": message_type,
        "post_id": post_id,
        "post_partial_url": post_partial_url,
    })

post_save.connect(
    post__on_post_save,
    sender=Post,
    dispatch_uid="post__on_post_save",
)

chat/models.py
import django.conf
from django.db import models
from django.conf import settings

class Room(models.Model):
    owner=models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="owned_room_set",
    )
    name=models.CharField(max_length=100)

    @property
    def chat_group_name(self):
        return self.make_chat_group_name(room=self)

    @staticmethod
    def make_chat_group_name(room=None, room_pk=None):
        return "chat-%s" % (room_pk or room.pk)

    #Room모델 수정: 셋에 default정렬 지정
    #대개 하나의 기준으로 정렬하는데 default로 지정 시 매번 정렬 필요 X
    class Meta:
        ordering=["-pk"]

chat/forms.py
from django import forms
from chat.models import Room

class RoomForm(forms.ModelForm):
    class Meta:
        model=Room
        fields=["name"]

accounts/views.py
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

login = LoginView.as_view(
    template_name = "partials/form.html",
    extra_context={
        "form_name": "로그인",
        "submit_label": "로그인",
    },
)

logout = LogoutView.as_view(
    next_page="accounts:login",
)

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

profile = ProfileView.as_view()

signup = CreateView.as_view(
    form_class=UserCreationForm,
    template_name="partials/form.html",
    extra_context={
        "form_name": "회원가입",
        "submit_label": "회원가입",
    },
    success_url=reverse_lazy("accounts:login"),
)

app/views.py
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, get_object_or_404

from app.models import Post


# Create your views here.
def echo_page(request):
 return render(request, "app/echo_page.html")

#Liveblog
#장고 템플릿 렌더링 통해 포스팅 목록을 렌더링
#HTML 페이지 전체를 렌더링
#템플릿 내에서 app/partial/post.html을 활용
#liveblog_index: post 모델에 대한 목록 페이지 구현

def liveblog_index(request:HttpRequest) -> HttpResponse:
 post_list = Post.objects.all()
 return render(request,"app/liveblog_index.html", {
  "post_list": post_list,
 })


#post_partial: 지정 포스트 id의 html만을 렌더링
def post_partial(request: HttpRequest, post_id) -> HttpResponse:
 post = get_object_or_404(Post,pk=post_id)
 return render(request,"app/partial/post.html",{
  "post":post,
 })

chat/views.py
import django.contrib.messages
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpRequest
from chat.forms import RoomForm
from chat.models import Room
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView

# Create your views here.
#index뷰 수정
#Room 목록 조회 후 chat/index.html템플릿을 통해 Room목록 렌더링
def index(request):
    #Room쿼리셋을 생성, context data로 room_list 이름으로 넘김
    room_qs = Room.objects.all()
    return render(request, "chat/index.html",{
        "room_list":room_qs,
    })


@login_required
def room_new(request):
    if request.method == "POST":
        form = RoomForm(request.POST)
        if form.is_valid():
            created_room: Room = form.save(commit=False)
            created_room.owner=request.user
            created_room.save()
            return redirect("chat:room_chat", created_room.pk)
    else:
        form = RoomForm()

    return render(request, "chat/room_form.html",{
        "form":form,
    })

@login_required
def room_chat(request:HttpRequest, room_pk: int)->HttpResponse:
    room=get_object_or_404(Room,pk=room_pk)
    return render(request,"chat/room_chat.html",{
        "room":room,
    })

@login_required
def room_delete(request:HttpRequest, room_pk: int)->HttpResponse:
    room = get_object_or_404(Room, pk=room_pk)

    if room.owner != request.user:
        messages.error(request, "채팅방 소유자가 아닙니다.")
        return redirect("chat:index")

    if request.method =="POST":
        room.delete()
        messages.success(request, "채팅방을 삭제했습니다.")
        return redirect("chat:index")

    return render(request, "chat/room_confirm_delete.html",{
        "room": room,
    })






# class RoomCreateView(LoginRequiredMixin, CreateView):
#     form_class = RoomForm
#     template_name = "chat/room_form.html"
#
#     def get_success_url(self):
#         created_room=self.object
#         return resolve_url("chat:room_chat", created_room.pk)
#
# room_new

accounts/templates/accounts/base.html
{% extends "base.html" %}

accounts/templates/accounts/profile.html
{% extends "accounts/base.html" %}
{% block extra-style %}
<style>
    .borderbox {
        border-color: rgb(224, 224, 224);
        border-style:double;
        border-radius: 0.8em;
        padding: 0.4em;
    }
</style>

{% endblock %}
{% block content %}
<div class="borderbox">
    <h3 class="p-4 text-info fw-bold ">{{ user.username }} 's profile 📝</h3>

    <ul class="fs-5 mt-4 text-info text-decoration-none fw-bold">
        <li>UserName : {{ user.username }}</li>
        <li>Last Login : {{ user.last_login }}</li>
    </ul>
</div>
{% endblock %}

app/templates/app/base.html
{% load django_bootstrap5 %}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8" >
    <title>Liveblog by django channels </title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <h1>Liveblog </h1>
    {% block content %}{% endblock %}

    {% block extra-body %}{% endblock %}
</body>
</html>

app/templates/app/echo_page.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Websocket Echo</title>
</head>
<body>

Websocket Echo..

<script>
    const ws = new WebSocket("ws://localhost:8000/ws/echo/");

    ws.onopen = () => {
        console.log("Connected to websocket server");
    };

    ws.onmessage  = (event) => {
        const message = event.data;
        console.log("message received:",message);
    };

    ws.onerror = () => {
        console.error("websocket error");
    };

    ws.onclose = (event) => {
        if(event.wasClean) {
            console.log("Disconnected by ws.close()");
        }else{
            console.log("Disconnected by network disconnection with Websocket server")
        }
    };

</script>

</body>
</html>

app/templates/app/liveblog_index.html
{% extends "app/base.html" %}
{% block content %}
    <div class="container">
        <h1>Hello </h1>

        <div class="row" id="post-list">
            {% for post in post_list %}
                {% include "app/partial/post.html" with post=post only %}
            {% endfor %}

        </div>
    </div>


{% endblock %}
{% block extra-body %}
    <script>
    const handlers={
        ws:null,
        connect(ws_url){
            this.ws = new WebSocket(ws_url);

            this.ws.onopen = this.onopen.bind(this);
            this.ws.onclose = this.onclose.bind(this);
            this.ws.onerror = this.onerror.bind(this);
            this.ws.onmessage = this.onmessage.bind(this);
        },
        onopen() {console.log("웹소켓 서버에 접속했습니다."); },
        onclose(event) {
            if(!event.wasClean) {
                console.error("웹소켓 서버가 죽거나 네트워크 장애입니다.")
            }
        },
        onerror() {console.error("웹소켓 에러 발생했습니다.");},
        onmessage(event) {
            const message_json = event.data;
            console.log("웹소켓 텍스트 메세지 수신: ", message_json);
            const { type, post_id, post_partial_url } = JSON.parse(message_json);

            switch(type) {
                case "liveblog.post.created":
                    this.post_created(post_id, post_partial_url);
                        break;
                case "liveblog.post.updated":
                    this.post_updated(post_id, post_partial_url);
                    break;
                case "liveblog.post.deleted":
                    this.post_deleted(post_id);
                    break;
                default:
                    console.error(`Invalid message type : ${type}`);
            }
        },
        post_created(post_id,post_partial_url){
            fetch(post_partial_url)
                .then(response => {
                    return response.text();
                })
                .then(html => {
                    document.querySelector("#post-list")
                        .insertAdjacentHTML("afterbegin", html)
                    });
        },
        post_updated(post_id, post_partial_url) {
            fetch(post_partial_url)
                .then(response => {
                    return response.text();
                })
                .then(html => {
                    const css_selector = `[data-post-id="${post_id}"]`;
                    document.querySelector(css_selector).outerHTML = html;
                });
        },
        post_deleted(post_id) {
            const css_selector = `[data-post-id="${post_id}"]`;
            document.querySelector(css_selector).remove();
        },
    };
    const ws_url="ws://localhost:8000/ws/liveblog/";
    handlers.connect(ws_url);
    </script>

{% endblock %}

app/templates/app/partial/post.html
<div class="col-sm-4" data-post-id="{{ post.id }}">
     <div class="card">
    <img src="https: /via.placeholder.com/572x360.png"
        alt="placeholder image"
        class="card-img-top" />
    <div class="card-body">
        <h5 class="card-title">
            #{{ post.id }}. {{ post.title }}
        </h5>
        <div class="card-text">
            {{ post.content|truncatewords:10 }}
        </div>
    </div>
 </div>
</div>

chat/templates/chat/base.html
{% extends 'base.html' %}

chat/templates/chat/index.html
{% extends "chat/base.html" %}
{% block content %}

 <h4 class="mt-5 pt-5 text-info border-top fw-bold"> ✉ Chat List </h4>
{#room_list 순회하며 room_chat 링크를 생성#}
 <ul class="mb-4">
 {% for room in room_list %}
     <li>
        <a href="{% url 'chat:room_chat' room.pk %} " class="fs-5 mt-5 text-info text-decoration-none">
            {{ room.name }} ➡
        </a>
     </li>
 {% endfor %}
 </ul>
    <a href="{% url 'chat:room_new' %}" class="fs-4 mt-5 text-info text-decoration-none fw-bold"> ✉ Start a NEW Chat </a>
{% endblock %}

chat/templates/chat/room_chat.html
{% extends "chat/base.html" %}

{% block extra-style %}
<style>
    .chat-message > div {
        background-color: #3b3b3d;
        color: #e1e1e1;
        border-radius: 0.8em;
        padding: 0.4em;
        margin: 0.4em 0;
        display: inline-block;
        white-space: pre-wrap;
        max-width: 80%;
        word-wrap: break-word;
    }
    .chat-message.me{
        text-align: right;
     }
    .chat-message.me >div{
        background-color: #1f8cff;
        color: #fff;
        text-align: left;
    }
</style>
{% endblock %}

{% block content %}
    <div class="container my-5">
        <div class ="row">
            <div class="col-sm-12">
                <div class="card" style="height: 600px; ">
                    <div class="card-header">
                        채팅방:{{ room.name }}
                    </div>
                    <div class="card-body overflow-hidden">
                        <div id="chat_messages" class="w-100 h-100 border-0 overflow-scroll"></div>
                    </div>
                    <div class="card-footer">
                        <form id="message_form">
                            <input type="text" name="message" class="form-control" autofocus autocomplete="off" />
                        </form>
                    </div>
                </div>
            <hr class="my-3"/>
            <a href="{% url 'chat:index' %}" class="btn btn-primary"> 대기실로 이동</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra-script %}
    <script>
    const handlers={
        chat_messages_tag : null,
        ws: null,
        retry: 0,

        init() {
            this.chat_messages_tag = document.querySelector("#chat_messages");
            document.querySelector("#message_form").addEventListener("submit", this.onsubmit.bind(this));
        },
        connect(ws_url){
            if(this.ws){ this.ws.close();}
            {#지정 주소로 웹소켓 연결 시도#}
            this.ws = new WebSocket(ws_url || this.ws?.url);
            this.ws.onopen = this.onopen.bind(this);
            this.ws.onclose = this.onclose.bind(this);
            this.ws.onerror = this.onerror.bind(this);
            this.ws.onmessage = this.onmessage.bind(this);
         },
        reconnect(){
            this.connect();
        },
        append_message(message, sender){
            const element = document.createElement("div");
            element.className = "chat-message";

            let footer="";
            if(sender==="{{ user.username }}"){
                element.className+=" me";
            }
            else if (sender){
                footer = ` from ${sender}`;
            }

            const wrapper = document.createElement("div");

            wrapper.textContent = message+footer;
            element.appendChild(wrapper);

            this.chat_messages_tag.appendChild(element);
            this.chat_messages_tag.scrollTop = this.chat_messages_tag.scrollHeight;
        },

        onsubmit(event) {
            event.preventDefault();

            const form_data = new FormData(event.target);
            const props = Object.fromEntries(form_data);
            event.target.reset();

            const { message } = props;
            console.log("웹소켓으로 전송할 메세지 :", message);

            this.ws.send(JSON.stringify({
                type : "chat.message",
                message : message,
             }))
        },
        onopen(){console.log("웹소켓 서버와 접속");this.retry=0;},

        onclose(event){
            if(!event.wasClean){
                console.error("웹소켓 서버가 죽었거나, 네트워크 장애입니다.");
                if(this.retry<3){
                    this.retry+=1;
                    setTimeout(() => {
                        this.reconnect();
                        console.log(`[${this.retry}] 접속 재시도 ...`);
                    }, 1000 * this.retry);
                }
                else{
                    console.log("웹소켓 서버에 접속할 수 없습니다. 대기실로 이동합니다.");
                    window.location.href="{% url 'chat:index' %}";
                }
            }
         },
        onerror(){
            console.log("웹소켓 에러가 발생했습니다. 대기실로 이동합니다.");
            window.location.href="{% url 'chat:index' %}";
         },
        onmessage(event){
            const message_json = event.data;
            console.log("메세지 수신: ", message_json);

            const message_obj = JSON.parse(message_json);
            const {type} = message_obj;

            switch (type){
                case "chat.message":
                    const {message, sender} = message_obj;
                    this.append_message(message, sender);
                    break;
                default:
                    console.error(`Invalid message type: ${type}`);
            }
         },
    };
    handlers.init();
    const protocol = location.protocol === "http:" ? "ws:" : "wss:";
    const ws_url = protocol + "//" + location.host + "/ws" + location.pathname;
    handlers.connect(ws_url)
    </script>
{% endblock %}

chat/templates/chat/room_confirm_delete.html
{% extends "chat/base.html" %}

{% block content %}
    <h2>{{ room.name }} 삭제하기</h2>

    <form action="" method="post">
        {% csrf_token %}
        <div class="alert alert-danger">삭제하시겠습니까?</div>
        <input type="submit" class="btn btn-primary" value="삭제하겠습니다."/>
    </form>
{% endblock %}

chat/templates/chat/room_form.html
{% extends "chat/base.html" %}
{% load django_bootstrap5 %}

{% block extra-style %}
<style>
    .borderbox {
        border-color: rgb(224, 224, 224);
        border-style:double;
        border-radius: 0.8em;
        padding: 1.5em;
    }
</style>

{% endblock %}

{% block content %}
<div class="borderbox">
    <h3 class="card-header text-info fw-bold"> 📨 새 채팅방 만들기 📨 </h3>

    <div class="my-3 card-header text-info fw-bold fs-4">
        <form action="" method="post">
            {% csrf_token %}

            {% bootstrap_form form %}
            <input type="submit" value="만들기" class="btn btn-info btn-lg text-white fw-bold"/>

        </form>

    </div>

    <a href="{% url 'chat:index' %}" class="btn btn-info btn-lg text-white fw-bold">대기실로 이동</a>
</div>

{% endblock %}

ecopschat/templates/base.html
{% load django_bootstrap5 %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width", user-scalable="no",initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>OUNCEs</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% block extra-style %}

    <style>

    </style>
    {% endblock %}

</head>

<body>

<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <div>
            <a href="/" class="d-flex align-items-center col-md-5 mb-md-0 text-info text-decoration-none fs-1 fw-bold">
                OUNCEs
            </a>
            <h5 class="d-flex align-items-center col-md-5 mb-2 mb-md-0 text-info text-decoration-none fw-bold">3IDIOTS</h5>
        </div>
    </header>
        <ul class="nav m-auto mb-2 justify-content-center mb-md-0 fw-bold">
            <li><a href="{% url 'chat:index' %}" class="nav-link link-dark text-info fs-4 ps-5 mb-2 "> 💎 Chat with Your ARTISTS 💎 </a> </li>
        </ul>
        <div class="d-flex m-auto align-items-center col-md-3 text-end mb-5 fw-bold">
                {% if not user.is_authenticated %}
                <a href="{% url 'accounts:login' %}" class="d-inline-block btn btn-outline-info m-5 btn-lg fw-bold">Log In</a>
                <a href="{% url 'accounts:signup' %}" class="btn btn-info btn-lg text-white fw-bold">Sign Up</a>
                {% else %}
                <a href="{% url 'accounts:profile' %}" class="d-inline-block btn btn-outline-info m-5 btn-lg fw-bold">Profile</a>
                <a href="{% url 'accounts:logout' %}" class=" btn btn-info btn-lg text-white fw-bold">Log Out</a>
                {% endif %}
        </div>
    {% bootstrap_messages %}

{% block content %}
    <h3 class="text-info fw-bold ">{{ form.name }}</h3>

    <div class ="card">
        {% if form_name %}
            <div class="card-header">{{ form_name }}</div>
        {% endif %}
        <div class="card-body">
            <form action="" method="post" novalidate>
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-info btn-lg text-white fw-bold" {% if submit_label %} value="{{ submit_label }}"{% endif %}/>
            </form>
        </div>
    </div>
{% endblock %}
</div>

{% block extra-script %}{% endblock %}
</body>
</html>

ecopschat/templates/partials/form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block extra-style %}

    <style>

    </style>
    {% endblock %}

{% block content %}
<h2 class="text-info fw-bold ">{{ form.name }}</h2>

<div class ="card">
    {% if form_name %}
        <div class="card-header text-info fw-bold fs-5">{{ form_name }}</div>
    {% endif %}
    <div class="card-body">
        <form action="" method="post" novalidate>
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-info btn-lg text-white fw-bold" {% if submit_label %} value="{{ submit_label }}"{% endif %}/>
        </form>
    </div>
</div>

{% endblock %}

ouncechat/templates/base.html
{% load django_bootstrap5 %}

<!doctype html>
<html lango=""ko>
<head>
    <meta charset="utf-8"/>
    <title>Django Channels</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% block extra-style %}{% endblock %}
</head>
<body>
    {% bootstrap_messages %}

    {% block content %}{% endblock %}
</body>
</html>